In [1]:
import numpy as np

from sklearn.linear_model import LogisticRegression

c:\ProgramData\Anaconda3\lib\site-packages\numpy\_distributor_init.py:30: UserWarning: loaded more than 1 DLL from .libs:
c:\ProgramData\Anaconda3\lib\site-packages\numpy\.libs\libopenblas.4SP5SUA7CBGXUEOC35YP2ASOICYYEQZZ.gfortran-win_amd64.dll
c:\ProgramData\Anaconda3\lib\site-packages\numpy\.libs\libopenblas.EL2C6PLE4ZYW3ECEVIV3OXXGRN2NRFM2.gfortran-win_amd64.dll
  warnings.warn("loaded more than 1 DLL from .libs:"


In [2]:
from sklearn.linear_model import LinearRegression

LinearRegression?

Init signature:
LinearRegression(
    *,
    fit_intercept=True,
    copy_X=True,
    n_jobs=None,
    positive=False,
)
Docstring:     
Ordinary least squares Linear Regression.

LinearRegression fits a linear model with coefficients w = (w1, ..., wp)
to minimize the residual sum of squares between the observed targets in
the dataset, and the targets predicted by the linear approximation.

Parameters
----------
fit_intercept : bool, default=True
    Whether to calculate the intercept for this model. If set
    to False, no intercept will be used in calculations
    (i.e. data is expected to be centered).

copy_X : bool, default=True
    If True, X will be copied; else, it may be overwritten.

n_jobs : int, default=None
    The number of jobs to use for the computation. This will only provide
    speedup in case of sufficiently large problems, that is if firstly
    `n_targets > 1` and secondly `X` is sparse or if `positive` is set
    to `True`. ``None`` means 1 unless in a
    :obj:`

## Steps for Logistic Regression

LR is similar with Linear Regression but instead of predict a continous value, LogReg predict the probability between 0 and 1 value

Training :
- Initialize weights as zero
- Initialize bias as zero

Given a data point:
- Predict result by using Logreg equation 
- calculate error
- use gradient descent to figure out new weight and bias values
- repeat n times



array([0., 0., 0., 0., 0.])

In [9]:
x = np.array([3,2,5,6,1])
weights = np.zeros(x.shape)

print(np.dot(x,weights))

0.0


In [10]:
weights


array([0., 0., 0., 0., 0.])

In [58]:
def sigmoid(x):
    return 1/(1 + np.exp(-x))

class LogisticReg():

    def __init__(self, lr=0.001, n_iters=1000):
        self.lr = lr
        self.n_iters= n_iters
        self.weights = None
        self.bias = None

    def fit(self, X, y):
        # mengambil banyaknya baris data dan attribute dari shape
        # setiap weight akan dikalikan dengan atribut sehingga ketika weight di inisiasi menjadi 0, kita harus memiliki matrix 0 yang...
        # ... berjumlah n_features data karena masing-masing atribut dikalikan dengan weight
        print('shape awal: ', X.shape)
        print('shape transpose: ', X.T.shape)
        n_samples, n_features = X.shape
        self.weights = np.zeros(n_features)
        print('shape weight 0: ', self.weights.shape)
        self.bias = 0 # bias langsung diinisiasi 0 karena dalam perhitungan tidak dikalikan dengan atribut namun hanya sebagai konstanta penjumlah

        for _ in range(self.n_iters):
            linear_pred = np.dot(X, self.weights) + self.bias
            prediction = sigmoid(linear_pred)

            dw = (1/n_samples) * np.dot(X.T, (prediction - y))
            db = (1/n_samples) * np.sum(prediction - y)

            self.weights = self.weights - self.lr*dw
            self.bias = self.bias - self.lr*db

    def predict(self,X):
        linear_pred = np.dot(X,self.weights) + self.bias
        y_pred = sigmoid(linear_pred) # y_pred adalah list probability hasil prediksi
        # print('y_pred = ', y_pred)

        label = [ 0 if y <= 0.5 else 1 for y in y_pred ]
        return label


        



In [47]:
from sklearn.model_selection import train_test_split
from sklearn import datasets

bc = datasets.load_breast_cancer()
X, y = bc.data, bc.target

X_train, X_test, y_train, y_test = train_test_split(X,y, test_size=0.2, random_state=123)

In [59]:
lr = LogisticReg(lr=0.0001)
lr.fit(X_train,y_train)

shape awal:  (455, 30)
shape transpose:  (30, 455)
shape weight 0:  (30,)


In [61]:
x = np.array([
    [1,2,3], 
    [4,5,6]])
y = np.array([
    [6,7,8],
    [6,5,4],
    [3,2,1]
])

print(x.shape)
print(y.shape)

(2, 3)
(3, 3)


In [69]:
np.dot(x,y)

array([[27, 23, 19],
       [72, 65, 58]])

In [53]:
def accuracy(y_pred, y_test):
    return (np.sum(y_pred==y_test))/len(y_test)

y_pred = lr.predict(X_test)
acc = accuracy(y_pred,y_test)
print(acc)


0.9473684210526315


In [ ]:
Pahami np.dot dan urutan parameternya

